# Directorio por defecto para copiar ROMs organizadas por carpetas
romraider.roms.default-folder=ROMRaider/roms

# Recordar usuario (usado por el login)
romraider.login.remember-me=true

# Tema oscuro de la aplicación
romraider.ui.dark-mode=false

# Al importar ROMs, buscar automáticamente datos en RAWG.io
romraider.api.autoupdate=true

# Idioma por defecto (ej: es, en, fr, de, etc.)
romraider.language=es
