RAWG_API_KEY=e6a0126080a14743825d61ecc3e5a349
SUPABASE_URL=https://zhvnanhftdtlqkmtiyaf.supabase.co
SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpodm5hbmhmdGR0bHFrbXRpeWFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDU3MjQsImV4cCI6MjA2NDI4MTcyNH0.pgI69yT5CDgSVh_EQhkmU4jIZY0zyOwkbTRHwQoLOxY
